spring.application.name=contract-watch
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/contract-bd
spring.datasource.username=root
spring.datasource.password=hari$5110$
